
SENSORS={
    0 : { type: 'S_DOOR', comment:'Door and window sensors', mappedToType: SensorTypes.S_DOOR },
    1 : { type: 'S_MOTION', comment:'Motion sensors',mappedToType: SensorTypes.S_MOTION },
    2 : { type: 'S_SMOKE', comment:'Smoke sensor',mappedToType: SensorTypes.S_SMOKE},
    3 : { type: 'S_LIGHT', comment:'Relay (on/off)',mappedToType: SensorTypes.S_LIGHT},
    4 : { type: 'S_DIMMER', comment:'Dimmable device of some kind',mappedToType: SensorTypes.S_DIMMER,},
    5 : { type: 'S_COVER', comment:'Window covers or shades',mappedToType: SensorTypes.S_COVER},
    6 : { type: 'S_TEMP', comment:'Temperature sensor', mappedToType: SensorTypes.S_TEMP},
    7 : { type: 'S_HUM', comment:'Humidity sensor', mappedToType: SensorTypes.S_HUM},
    8 : { type: 'S_BARO', comment:'Barometer sensor (Pressure)', mappedToType: SensorTypes.S_BARO},
    9 : { type: 'S_WIND', comment:'Wind sensor', mappedToType: SensorTypes.S_WIND},
    10 : { type: 'S_RAIN', comment:'Rain sensor', mappedToType: SensorTypes.S_RAIN},
    11 : { type: 'S_UV', comment:'UV sensor', mappedToType: SensorTypes.S_UV},
    12 : { type: 'S_WEIGHT', comment:'Weight sensor for scales etc.', mappedToType: SensorTypes.S_WEIGHT},
    13 : { type: 'S_POWER', comment:'Power measuring device, like power meters',mappedToType: SensorTypes.S_POWER},
    14 : { type: 'S_HEATER', comment:'Heater device',mappedToType: SensorTypes.S_HEATER},
    15 : { type: 'S_DISTANCE', comment:'Distance sensor', mappedToType: SensorTypes.S_DISTANCE},
    16 : { type: 'S_LIGHT_LEVEL', comment:'Light sensor', mappedToType: SensorTypes.S_LIGHT_LEVEL},
    17 : { type: 'S_ARDUINO_NODE', comment:'Arduino node device',mappedToType: SensorTypes.S_ARDUINO_NODE},
    18 : { type: 'S_ARDUINO_REPEATER_NODE', comment:'Arduino repeating node device',mappedToType: SensorTypes.S_ARDUINO_REPEATER_NODE},
    19 : { type: 'S_LOCK', comment:'Lock device'},
    20 : { type: 'S_IR', comment:'Ir sender/receiver device'},
    21 : { type: 'S_WATER', comment:'Water meter', mappedToType: SensorTypes.S_WATER},
    22 : { type: 'S_AIR_QUALITY', comment:'Air quality sensor e.g. MQ-2'},
    23 : { type: 'S_CUSTOM', comment:'custom sensors where no other fits.'},
    24 : { type: 'S_DUST', comment:'Dust level sensor'},
    25 : { type: 'S_SCENE_CONTROLLER', comment:'Scene controller device'},
    26 : { type: 'S_RGB_LIGHT', comment:'RGB light'},
    27 : { type: 'S_RGBW_LIGHT', comment:'RGBW light (with separate white component)'},
    28 : { type: 'S_COLOR_SENSOR', comment:'Color sensor'},
    29 : { type: 'S_HVAC', comment:'Thermostat/HVAC device'},
    30 : { type: 'S_MULTIMETER', comment:'Multimeter device'},
    31 : { type: 'S_SPRINKLER', comment:'Sprinkler device'},
    32 : { type: 'S_WATER_LEAK', comment:'Water leak sensor'},
    33 : { type: 'S_SOUND', comment:'Sound sensor'},
    34 : { type: 'S_VIBRATION', comment:'Vibration sensor'},
    35 : { type: 'S_MOISTURE', comment:'Moisture sensor'},
   100 : { type: 'S_PH', comment:'pH sensor',mappedToType: SensorTypes.S_PH}

};
